name: CI

on:
  push:
    branches:
      - master
  pull_request:
    brances:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/clover.xml
      - run: yarn install
      - run: yarn test
