name: CI

on:
  push:
    branches:
    - master
  pull_request:
    brances:
    - master

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install node_modules
      run: yarn install
    - name: Test
      run: yarn test
